pull_request_rules:
- actions:
    queue:
      name: not <h1>exists</h1> !!
  conditions:
  - base=20221201092410/test_invalid_config_html_escape/main
  - label=<h1>foo</h1>bar
  name: no <i>manual</i> merge
