jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: "Success step \U0001F389"
      run: echo toto
    - continue-on-error: true
      name: "Failed step but no failure \U0001F6D1"
      run: echo I fail but we continue;exit 1
    - name: "Failure step with *\"/\\<>:|? in the title \u274C"
      run: echo I will fail on sha ${{ github.event.pull_request.head.sha }} run_attempt:${{
        github.run_attempt }};exit 1
    timeout-minutes: 5
name: Continuous Integration
'on':
  pull_request:
    branches: 20231230204146/test_log_embedding/main
