jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Fail until run_attempt 2
      run: echo I will fail on sha ${{ github.event.pull_request.head.sha }} and if
        run_attempt is lower than 2 run_attempt:${{ github.run_attempt }};[[ ${{ github.run_attempt
        }} -lt 2 ]] && exit 1 || exit 0
    timeout-minutes: 5
name: Continuous Integration
'on':
  pull_request:
    branches: 20231127185504/test_rerun_on_known_flaky/main
