jobs:
  unit-tests:
    runs-on: dummy_runner
    steps:
    - name: Say hi we count run_attempt here
      run: echo I will fail on sha ${{ github.event.pull_request.head.sha }} run_attempt:${{
        github.run_attempt }};exit 1
    timeout-minutes: 5
name: Continuous Integration
'on':
  pull_request:
    branches: 20240318150659/test_log_downloading_with_no_steps/main
