jobs:
  job_without_matrix:
    runs-on: ubuntu-20.04
    steps:
    - name: No matrix
      run: echo no matrix
    timeout-minutes: 5
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: 'run version: ${{ matrix.version }} os:${{ matrix.os }}'
      run: 'echo version: ${{ matrix.version }} os:${{ matrix.os }}'
    strategy:
      matrix:
        os:
        - windows
        - mac
        version:
        - 2.8
        - 3.5
    timeout-minutes: 5
name: Continuous Integration
'on':
  pull_request:
    branches: 20240318150852/test_workflow_job_ingestion_with_matrix/main
