jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Show author
      run: echo author=${{ inputs.author }}
name: dynamic_workflow
'on':
  pull_request:
    branches: 20231204115919/test_gha_with_template_input/main
  workflow_dispatch:
    inputs:
      author:
        required: true
        type: string
